apiVersion: v1
kind: Service
metadata:
  labels:
    name: emiliabastien-app
  name: emiliabastien-app-svc
  namespace: emiliabastien
spec:
  type: LoadBalancer
  selector:
    app: emiliabastien-app
  ports:
  - name: http
    protocol: TCP
    port: 3000
    #nodePort: 30001
    targetPort: 3000
